// generated by tools/gen_ranks.py from docs/RANGI.txt - do not edit
#include "ui/ranks.h"

#include "ui/lang.h"

namespace cr {

// { English, Polish, Spanish, Latin, Czech, Slovak, Hungarian, Romanian, Volapuk, Esperanto } for levels 1-1 up (index = level - 1)
static const char *const kRanks[35][10] = {
    {"Speed Bump", "Prog Zwalniajacy", "Badén", "Gibbus Viae", "Zpomalovací práh", "Spomaľovač", "Fekvőrendőr", "Limitator de viteză", "Stopöm Vega", "Rapidobaro"},
    {"Road Snack", "Przekaska dla Tira", "Aperitivo de Camión", "Cibus Plaustri", "Svačinka pro kamion", "Desiata pre kamión", "Kamionuzsonna", "Gustare pentru camion", "Zibil Kamiona", "Manĝeto por Kamiono"},
    {"Professional Tree Hugger", "Zawodowy Przytulacz Drzew", "Abrazaárboles Profesional", "Amplexator Arborum", "Profesionální objímač stromů", "Profesionálny objímač stromov", "Hivatásos faölelő", "Îmbrățișător de copaci", "Bimigleban Calik", "Profesia Arbobrakumulo"},
    {"Accidental Pedestrian", "Przypadkowy Przechodzien", "Peatón Accidental", "Pedes Fortuitus", "Náhodný chodec", "Náhodný chodec", "Véletlen gyalogos", "Pieton întâmplător", "Futan Fädik", "Hazarda Piediranto"},
    {"Almost Roadkill", "Prawie Rozjechany", "Casi Atropellado", "Paene Contritus", "Skoro přejetý", "Skoro prejdený", "Majdnem elütött", "Aproape călcat", "Ti Pedrefölöl", "Preskaŭ Dispremita"},
    {"Puddle Jumper", "Skoczek przez Kaluze", "Saltacharcos", "Saltator Lacunarum", "Skokan přes louže", "Skokan cez mláky", "Tócsaugró", "Săritor peste bălți", "Bunan Lulakas", "Flaksaltanto"},
    {"Log Surfer Trainee", "Stazysta na Klodzie", "Aprendiz de Surfista de Troncos", "Tiro Truncorum", "Učeň surfař na kládě", "Učeň surfista na klade", "Rönkszörf-tanonc", "Ucenic surfer pe bușteni", "Lärnan Bimasörfa", "Lernanto de Ŝtipsurfado"},
    {"Crosswalk Rookie", "Swiezak na Pasach", "Novato del Paso de Cebra", "Tiro Transitus", "Nováček na přechodu", "Nováčik na priechode", "Zebrán kezdő", "Începător pe trecere", "Nulan Lovegolöpa", "Novulo ĉe Transirejo"},
    {"Bumper Dodger", "Unikacz Zderzakow", "Esquivaparachoques", "Vitator Plaustrorum", "Uhýbač nárazníků", "Uhýbač nárazníkov", "Lökhárító-kerülő", "Evitator de bare", "Vitan Stödabas", "Evitanto de Bufroj"},
    {"Critter with a Plan", "Zwierzak z Planem", "Bicho con un Plan", "Bestiola cum Consilio", "Zvířátko s plánem", "Zvieratko s plánom", "Állatka tervvel", "Vietate cu plan", "Nimülil ko Plan", "Besteto kun Plano"},
    {"Traffic Whisperer", "Zaklinacz Ruchu", "Susurrador del Tráfico", "Susurrator Viarum", "Zaříkávač dopravy", "Zaklínač dopravy", "Forgalomsuttogó", "Îmblânzitor de trafic", "Lüvokan Tafa", "Flustranto al Trafiko"},
    {"Lily Pad Captain", "Kapitan Lilii", "Capitán de los Nenúfares", "Centurio Nymphaearum", "Kapitán leknínů", "Kapitán leknínov", "Tavirózsa-kapitány", "Căpitan de nuferi", "Kapiten Nümfäas", "Kapitano de Nimfeoj"},
    {"Rail Dancer", "Tancerz na Torach", "Bailarín de las Vías", "Saltator Ferriviae", "Tanečník na kolejích", "Tanečník na koľajniciach", "Síntáncos", "Dansator pe șine", "Dansan su Rels", "Dancisto sur Reloj"},
    {"Roadside Ninja", "Ninja z Pobocza", "Ninja de la Cuneta", "Ninja Marginis", "Silniční ninja", "Cestný nindža", "Útszéli nindzsa", "Ninja de pe marginea drumului", "Ninja Vegabörda", "Vojranda Ninĝo"},
    {"Crossing Veteran", "Weteran Przejsc", "Veterano de los Cruces", "Veteranus Transituum", "Veterán přechodů", "Veterán priechodov", "Átkelő-veterán", "Veteran al trecerilor", "Veteran Lovegolas", "Veterano de Transiroj"},
    {"Asphalt Acrobat", "Akrobata Asfaltu", "Acróbata del Asfalto", "Petaurista Bituminis", "Asfaltový akrobat", "Asfaltový akrobat", "Aszfaltakrobata", "Acrobat de asfalt", "Kobatan Sfalta", "Asfalta Akrobato"},
    {"River Tamer", "Pogromca Rzeki", "Domador del Río", "Domitor Fluminis", "Krotitel řek", "Krotiteľ riek", "Folyószelídítő", "Îmblânzitor de râuri", "Mekan Flumas Libik", "Riverdresisto"},
    {"Train Teaser", "Ten, co Drazni Pociagi", "Provocador de Trenes", "Lacessitor Traminum", "Škádlič vlaků", "Podpichovač vlakov", "Vonatugrató", "Tachinător de trenuri", "Tupan Trenas", "Incitanto de Trajnoj"},
    {"Sergeant Snout", "Sierzant Ryjek", "Sargento Hocico", "Optio Rostrum", "Seržant Čumák", "Seržant Ňufák", "Pofa őrmester", "Sergent Bot", "Serjan Snut", "Serĝento Muzelo"},
    {"Boss of the Street", "Szef Ulicy", "Jefe de la Calle", "Dominus Viae", "Šéf ulice", "Šéf ulice", "Az utca főnöke", "Șeful străzii", "Cif Süta", "Estro de la Strato"},
    {"Highway Hero", "Bohater Autostrady", "Héroe de la Autopista", "Heros Viae Publicae", "Hrdina dálnice", "Hrdina diaľnice", "Autópálya-hős", "Erou al autostrăzii", "Hiel Gretavega", "Heroo de la Aŭtovojo"},
    {"Captain Crossroads", "Kapitan Skrzyzowanie", "Capitán Encrucijada", "Centurio Trivii", "Kapitán Křižovatka", "Kapitán Križovatka", "Kereszteződés kapitány", "Căpitanul Intersecție", "Kapiten Vegakrod", "Kapitano Vojkruciĝo"},
    {"Lord of the Logs", "Wladca Klod", "Señor de los Troncos", "Dominus Truncorum", "Pán klád", "Pán kmeňov", "A rönkök ura", "Stăpânul buștenilor", "Söl Bimas", "Sinjoro de la Ŝtipoj"},
    {"Major Mayhem", "Major Zamieszanie", "Comandante Caos", "Tribunus Tumultus", "Major Zmatek", "Major Zmätok", "Káosz őrnagy", "Maiorul Haos", "Majoran Konfud", "Majoro Kaoso"},
    {"Commander of Crossings", "Komendant Przejsc", "Comandante de los Cruces", "Legatus Transituum", "Velitel přechodů", "Veliteľ priechodov", "Átkelők parancsnoka", "Comandantul trecerilor", "Komandan Lovegolas", "Komandanto de Transiroj"},
    {"Iron Nerve", "Zelazne Nerwy", "Nervios de Acero", "Nervi Ferrei", "Železné nervy", "Železné nervy", "Acélideg", "Nervi de oțel", "Nörvs Ferik", "Fera Nervo"},
    {"Storm on Legs", "Burza na Nozkach", "Tormenta con Patas", "Tempestas Pedestris", "Bouře na nohou", "Búrka na nohách", "Lábon járó vihar", "Furtună pe picioare", "Tem su Futs", "Ŝtormo sur Piedoj"},
    {"General Gridlock", "General Korek", "General Atasco", "Imperator Obstructionis", "Generál Zácpa", "Generál Zápcha", "Dugó tábornok", "Generalul Ambuteiaj", "General Blockam", "Generalo Ŝtopiĝo"},
    {"Drivers' Nightmare", "Postrach Kierowcow", "Pesadilla de los Conductores", "Terror Aurigarum", "Noční můra řidičů", "Nočná mora vodičov", "A sofőrök rémálma", "Coșmarul șoferilor", "Neitajäd Vabanas", "Koŝmaro de Ŝoforoj"},
    {"Master of the Road", "Mistrz Drogi", "Maestro del Camino", "Magister Viae", "Mistr silnice", "Majster cesty", "Az út mestere", "Maestrul drumului", "Mastan Vega", "Majstro de la Vojo"},
    {"Legend of the Lane", "Legenda Pasa", "Leyenda del Carril", "Fabula Semitae", "Legenda pruhu", "Legenda pruhu", "A sáv legendája", "Legenda benzii", "Liedäd Vegadila", "Legendo de la Leno"},
    {"Myth of the Motorway", "Mit Autostrady", "Mito de la Autopista", "Mythus Viae Regiae", "Mýtus dálnice", "Mýtus diaľnice", "Az autópálya mítosza", "Mitul autostrăzii", "Mit Gretavega", "Mito de la Aŭtovojo"},
    {"Golden Step", "Zloty Krok", "Paso de Oro", "Gradus Aureus", "Zlatý krok", "Zlatý krok", "Aranylépés", "Pasul de aur", "Stäp Goldik", "Ora Paŝo"},
    {"Supreme Crosser", "Najwyzszy Przechodzien", "Cruzador Supremo", "Transitor Supremus", "Nejvyšší přecházeč", "Najvyšší prechádzač", "Legfőbb átkelő", "Traversorul suprem", "Lovegolan Muik", "Supera Transiranto"},
    {"The One Who Crossed", "Ten, Ktory Przeszedl", "El Que Cruzó", "Qui Transiit", "Ten, který přešel", "Ten, ktorý prešiel", "Aki átkelt", "Cel care a trecut", "Utan Kel Elovegolom", "Tiu Kiu Transiris"},
};
static const char *const kTopRank[10] = {"Unkillable Legend", "Niesmiertelna Legenda", "Leyenda Inmortal", "Fabula Immortalis", "Nesmrtelná legenda", "Nesmrteľná legenda", "Halhatatlan legenda", "Legenda nemuritoare", "Liedäd Nedeadik", "Nemortigebla Legendo"};

int rankCount() { return 35; }

const char *rankName(int level)
{
    const int i = level - 1;
    return i < 0 ? kRanks[0][lang::current()] : i < 35 ? kRanks[i][lang::current()]
                                                                 : kTopRank[lang::current()];
}

} // namespace cr
