// Screens drawn over the game (src/screens/*.tsx and the overlays of src/app/index.tsx). Animations advance per
// logic step (1/60 s), so a replay shows the same frames. Implemented: Home (4.2b) with the mode menu of O11.2,
// Game Over and the restart fade (4.2c), Pause (4.2d) and Settings (4.2e) — the last two are the port's own,
// styled like SettingsScreen.
#pragma once

#include <functional>
#include <string>

#include "engine/input.h"
#include "engine/renderer.h"
#include "engine/text.h"
#include "ui/lang.h"

namespace cr {

class Game;

// src/Characters.ts: the original ships only the chicken enabled; the other six are commented out there but their
// models are in the game (task 7.1 makes them selectable)
struct CharacterInfo {
    const char *id;
    const char *name;
};
// O14: the beaver is ours - generated by tools/make_beaver.py, not taken from anyone else's model - and since O15
// it is the game's own hero, with the chicken kept as one of the alternatives
// The Amiga's compiler (gcc 6.5) stops at C++14 and has no inline variables; a const array at namespace scope has
// internal linkage anyway, so there it is simply `static`. Every C++17 build sees the line it always had.
#if __cplusplus >= 201703L
inline
#else
static
#endif
const CharacterInfo kCharacters[] = {{"beaver", "BEAVER"},     {"chicken", "CHICKEN"},   {"bacon", "BACON"},
                                            {"brent", "BRENT VATNE"}, {"avocoder", "AVOCODER"}, {"wheeler", "WHEELER"},
                                            {"palmer", "PALMER"},     {"juwan", "JUWAN"}};
constexpr int kCharacterCount = 8;

// what the settings screen edits; saved in conf/crossy.cfg by the app
struct UserSettings {
    int volume = 10;   // 0..10, sound effects
    // 0..10 like the sounds (the author: one scale for both); the platforms play it at music * 10 percent. It was a
    // percentage in steps of 2 - the config keeps it as music_level now, an old music_volume read once (22 -> 2).
    int music = 2;
    int shadows = 0;   // 0 full, 1 simple, 2 off
    bool fpsCounter = false;
    int framing = 0;   // 0 normal (view scale 3), 1 wide (3.5)
    int character = 0; // 7.1: index into kCharacters
    int language = 0;  // O11.5: 0 English, 1 Polish, 2 Spanish, 3 Latin (ui/lang.h)
    // O23: how many play, and which input device each of them uses. The devices are the platform's own - the app
    // hands their names to Screens::controlNames - so this screen works the same on a keyboard and on a console.
    int players = 1;
    int control[2] = {0, 1};
    // O24: instead of forcing one or two in here, the Players entry has a third state - the home screen then asks
    // how many, every time, and `players` above is the answer it remembers.
    bool askPlayers = false;
    // O24: Progression until it is beaten. A dead player comes back instead of the level ending.
    bool infiniteRespawn = false;
    // The Amiga's screen shape: 0 the whole screen, 1 narrow, 2 a tall "phone" column - the scene zoomed out with
    // sprite sets of its own. Only where the platform sets Screens::viewShapes; everywhere else it stays 0, unseen.
    int shape = 0;
    // Night mode: the whole picture warmed like a lamp of that colour temperature - 0 off, 1 4200 K, 2 2700 K,
    // 3 1900 K (a candle). The Amiga filters its palette; the consoles tint what they render.
    int night = 0;
};

struct MenuResult {
    bool resume = false, quitToHome = false, exitGame = false, settingsChanged = false;
    // O24: the home screen asked how many play and got an answer (0 = it did not ask). The app applies this
    // BEFORE startLevel, because the player count decides the map and which career is being continued.
    int players = 0;
    // O11.2: the home screen picked a game — 0 = Classic, k > 0 = Progression level k; -1 = nothing picked
    int startLevel = -1;
    // O11.4: New Game was confirmed, so the saved Progression progress goes back to level 1
    bool resetCareer = false;
};

enum class Menu { None, Pause, Settings };

// O23: the settings screen is a SCROLLING list now - the two control entries do not fit on one screenful, and the
// user asked for exactly this ("musimy chyba zrobic przewijane menu"). The order is the order they are shown in.
enum SettingsItem {
    SetPlayers, SetControl1, SetControl2, SetRespawn, SetSounds, SetMusic, SetView, SetLanguage, SetCharacter,
    SetShadows, SetFps, SetBack, SetShape, SetNight, SetItemCount
};

class Screens {
public:
    bool load(Renderer &renderer, const std::string &dataDir);

    // once per logic step
    void update(const Game &game);
    void draw(Renderer &renderer, TextRenderer &text, const Game &game, int screenW, int screenH);
    // transitionToGamePlayingState: the GL view fades out (200 ms) and back in (300 ms) on restart; draw right
    // after the 3D scene, before the HUD (the score is outside the faded view in the original)
    void drawSceneFade(Renderer &renderer, int screenW, int screenH);

    void openPause();
    void openSettings(bool fromPause);
    Menu menu() const { return menu_; }
    // the game must not step: the pause menu, or settings opened from it
    bool pausesGame() const { return menu_ == Menu::Pause || (menu_ == Menu::Settings && settingsFromPause_); }
    // the restart fade is on screen (the Amiga's narrow views draw such frames on the whole screen)
    bool fading() const { return fadeTime_ >= real(0); }
    // an open menu or the home screen takes the step's input first; true = consumed, the game must not see it
    bool handleInput(const Input &input, UserSettings &settings, MenuResult &out);

    // UI sounds (banner, buttons) for the audio mixer
    std::function<void(const std::string &)> playSound;
    // current values shown by the settings screen
    const UserSettings *settings = nullptr;
    // O11.4: the Progression level the player may start (1 = nothing finished yet); the app keeps it in its config
    int careerLevel = 1;
    // shown small in the corner of the home screen when set (the SF2000 build: the user tests by version number)
    std::string versionLabel;
    // The platform draws the scene in several screen shapes (the Amiga): the settings then offer UserSettings::shape.
    // Off by default, so a platform that does not set it keeps exactly the settings it always had.
    bool viewShapes = false;
    // The title screen's menu gets a third bar, SETTINGS, below Classic and Progression (the Amiga: a keyboard
    // player should not have to know that S opens them). Every port turns it on now; off by default.
    bool homeSettings = false;
    // The platform has only simple shadows (the Amiga): the Shadows entry offers SIMPLE and OFF, and a stored FULL
    // reads as SIMPLE. Off by default.
    bool simpleShadowsOnly = false;
    // The pause and settings menus as a WINDOW with a solid background (the Amiga): a strip of the frozen game stays
    // visible above (menuGapTop) and below (menuGapBottom), in logical pixels, and nothing else is drawn under the
    // window. The dithered see-through backdrop is the slowest thing a menu draws there. Off by default.
    bool solidMenus = false;
    int menuGapTop = 20, menuGapBottom = 8;
    // the title's first page, where there is nothing left to go back to (the Amiga's Esc then leaves the game)
    bool atHomeTop() const { return homePage_ == HomePage::Modes; }
    // O23: the input devices this platform offers, in the order the settings screen steps through them (for example
    // ARROWS, WSAD, JOY 1, JOY 2). Left null on a platform with one device, and the control entries then vanish.
    const char *const *controlNames = nullptr;
    int controlCount = 0;
    // Windows: which of those devices can be chosen right now (a pad slot with nothing plugged in cannot). Stepping
    // through the list skips the others; a player whose pad was unplugged keeps it and sees its name for "missing".
    // Null (every other platform) = all of them, as before.
    const bool *controlAvailable = nullptr;

    // Windows: the hints and the labels by the buttons name the keyboard key as well as the pad button
    // ("A/ENTER", "B/ESC", "SELECT/TAB"). Off everywhere else: the consoles keep exactly their text.
    bool keyboardHints = false;
    // Windows (mouse and touch): a pause button during play and a back arrow wherever only B went back, so every
    // screen can be worked by tapping. Off everywhere else.
    bool pointerUi = false;
    // A click or tap at (x, y) in the overlay's logical pixels (what draw() gets as its w x h). Returns the buttons it
    // stands for - the app presses them for one step through the same road a pad takes - after moving the cursor of
    // the list it hit, so A / Left / Right then act on that row. 0 = it hit the screens but means nothing,
    // kPointerField = it hit nothing the screens own (the play field: taps and swipes there are hops).
    static const int kPointerField = -1;
    int pointerTap(int x, int y, const Game &game, int w, int h);
    // would a press at (x, y) land on something the screens own (so it must not start a hop)?
    bool pointerOnUi(int x, int y, const Game &game, int w, int h) const;
    // the mouse wheel or a vertical swipe over the settings list: moves it by `rows` (the cursor stays on screen)
    void pointerScroll(int rows, int h);

private:
    void drawHome(Renderer &renderer, TextRenderer &text, int screenW, int screenH);
    void drawGameOver(Renderer &renderer, TextRenderer &text, const Game &game, int screenW, int screenH);
    void drawPause(Renderer &renderer, TextRenderer &text, int screenW, int screenH);
    void menuWindow(Renderer &renderer, int screenW, int screenH); // the backdrop, or the solid window
    void drawSettings(Renderer &renderer, TextRenderer &text, int screenW, int screenH);
    // O11.2: the game over screen's banners, in the home screen's colours, as menu items
    void drawMenuBars(Renderer &renderer, TextRenderer &text, const std::string *labels, int count, int cursor, int w,
                      int top, int barH = 48, int gap = 14);
    // O24: the pulsing bar that marks the selected row of the pause and settings lists
    void selectionBar(Renderer &renderer, int w, int y, int size);
    bool handleHome(const Input &input, MenuResult &out);
    // O23: which entries the settings screen shows right now (the second control only with two players, and no
    // control entries at all when the platform offers one device); returns how many
    int settingsItems(const UserSettings &s, SettingsItem *out) const;
    // how many rows of the list fit between the title and the hint line
    static int visibleRows(int h);
    // O24: does the home screen ask how many play before a game starts?
    bool askingPlayers() const { return settings && settings->askPlayers; }
    static lang::Str settingsLabel(SettingsItem item);
    bool controlUsable(int v) const { return !controlAvailable || controlAvailable[v]; }
    // keyboardHints: "A START   SELECT SETTINGS" -> "A/ENTER START   SELECT/TAB SETTINGS" (each part of a hint starts
    // with its button's name, in every language); a label by a button likewise
    std::string hintText(const std::string &hint) const;
    std::string buttonLabel(const char *button) const;
    // a hint line, centred; too wide for the screen (keyboardHints only) it takes two lines, ending at the same place
    void drawHint(Renderer &renderer, TextRenderer &text, const std::string &hint, int w, int y, int size) const;
    // pointerUi: the back arrow (the settings screen's image) with its label under it
    void drawBackButton(Renderer &renderer, TextRenderer &text, int x, int y) const;
    void drawPauseButton(Renderer &renderer, int w) const;
    // the element under (x, y), without acting on it: 0 none, else one of the kHit values in screens.cpp
    int pointerHit(int x, int y, const Game &game, int w, int h, int *index) const;
    std::string settingsValue(SettingsItem item, const UserSettings &s) const;

    // O11.2/O11.4: what the home screen shows — the two modes, the career menu behind Progression, and the
    // confirmation New Game needs before the saved progress goes
    // O24: Players sits between the modes and the career, so by the time the career page appears the game knows
    // which of the two careers (one player or two) it is showing.
    enum class HomePage { Modes, Players, Career, Confirm };

    Menu menu_ = Menu::None;
    bool settingsFromPause_ = false;
    int cursor_ = 0;
    int scrollTop_ = 0; // O23: first list row on screen
    // B pressed while this menu was open. The pause menu resumes on B's RELEASE, and on Windows Esc is both Start
    // (which opened the pause) and B: without this its release closed the menu the same press had opened.
    bool bSeen_ = false;
    HomePage homePage_ = HomePage::Modes;
    int homeCursor_ = 0, careerCursor_ = 0, confirmCursor_ = 0, playersCursor_ = 0;
    int pendingMode_ = 0; // O24: which mode the Players page is answering for (0 Classic, 1 Progression)
    GpuTexture title_, buttonPlay_, buttonSettings_, buttonBack_;
    int lastState_ = -1;
    real stateTime_ = 0;   // seconds since the game state last changed
    real pageTime_ = 0;    // seconds since the home screen's page last changed (the bars' entry)
    // O24: the selected row's bar pulses between two colours so the eye finds it. A plain counter of logic steps,
    // not a time in seconds: it never overflows 16.16 fixed point, however long a menu is left open.
    int blinkSteps_ = 0;
    static const int kBlinkPeriod = 30; // steps; 30 at 60 Hz is two full pulses a second
    bool blinkOn() const { return blinkSteps_ < kBlinkPeriod / 2; }
    int homeVisits_ = 0;   // HomeScreen mounts
    int bestAtStart_ = 0;  // highscore when the current game started (NEW BEST)
    real fadeTime_ = -1;   // seconds into the restart fade, -1 = none
};

} // namespace cr
