#!/usr/bin/env python3
"""docs/RANGI.txt (the user's approved rank list) -> src/ui/ranks.cpp.

    python tools/gen_ranks.py

Lines look like "1-1 | Egg on Legs | Jajko na nozkach", one per level, and the last one ("8-1+") is the single
maximum rank every level from 8-1 on carries. Regenerate after editing the list; the file is checked in.
"""
import os
import re
import sys

LINE = re.compile(r"^\s*(\d+)-(\d+)(\+?)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*$")
MORE = re.compile(r"^\s*(\d+)-(\d+)(\+?)\s*\|\s*(.+?)\s*$")


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(root, "docs", "RANGI.txt")
    ranks, top = [], None
    for line in open(src, encoding="utf-8"):
        # the file ends with a "was -> is" table whose rows start with a level too; stop before it
        if line.startswith("====") and "BYLO" in line.upper().replace("Ł", "L"):
            break
        m = LINE.match(line)
        if not m or "->" in line:
            continue
        world, stage, plus, english, polish = m.groups()
        if plus:
            top = (english, polish)
        else:
            level = (int(world) - 1) * 5 + int(stage)
            if level != len(ranks) + 1:
                print(f"gen_ranks: {src} jumps from level {len(ranks)} to {world}-{stage}")
                return 1
            ranks.append((english, polish))
    if top is None or not ranks:
        print(f"gen_ranks: {src} has no ranks")
        return 1

    # Spanish and Latin (docs/RANGI_ES_LA.txt), then Czech, Slovak, Hungarian, Romanian, Volapuk and Esperanto
    # (docs/RANGI_CS_SK_HU_RO_VO_EO.txt): "level | lang | lang ...", level by level, in the order of lang.h
    for name, width in (("RANGI_ES_LA.txt", 2), ("RANGI_CS_SK_HU_RO_VO_EO.txt", 6)):
        src2 = os.path.join(root, "docs", name)
        more, more_top = [], None
        for line in open(src2, encoding="utf-8"):
            m = MORE.match(line)
            if not m:
                continue
            cols = [c.strip() for c in m.group(4).split("|")]
            if len(cols) != width:
                print(f"gen_ranks: {src2}: {len(cols)} columns instead of {width}: {line.strip()}")
                return 1
            if m.group(3):
                more_top = tuple(cols)
            else:
                more.append(tuple(cols))
        if len(more) != len(ranks) or more_top is None:
            print(f"gen_ranks: {src2} has {len(more)} ranks, {src} has {len(ranks)}")
            return 1
        ranks = [r + m for r, m in zip(ranks, more)]
        top = top + more_top
    n = len(top)

    out = ['// generated by tools/gen_ranks.py from docs/RANGI.txt - do not edit', '#include "ui/ranks.h"', "",
           '#include "ui/lang.h"', "", "namespace cr {", "",
           f"// {{ English, Polish, Spanish, Latin, Czech, Slovak, Hungarian, Romanian, Volapuk, Esperanto }} for levels 1-1 up (index = level - 1)",
           f"static const char *const kRanks[{len(ranks)}][{n}] = {{"]
    for r in ranks:
        out.append("    {" + ", ".join(f'"{x}"' for x in r) + "},")
    out.append("};")
    out.append(f"static const char *const kTopRank[{n}] = {{" + ", ".join(f'"{x}"' for x in top) + "};")
    out.append("")
    out.append(f"int rankCount() {{ return {len(ranks)}; }}")
    out.append("")
    out.append("const char *rankName(int level)")
    out.append("{")
    out.append("    const int i = level - 1;")
    out.append(f"    return i < 0 ? kRanks[0][lang::current()] : i < {len(ranks)} ? kRanks[i][lang::current()]")
    out.append("                                                                 : kTopRank[lang::current()];")
    out.append("}")
    out.append("")
    out.append("} // namespace cr")
    dst = os.path.join(root, "src", "ui", "ranks.cpp")
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"gen_ranks: {len(ranks)} ranks + one maximum -> {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
